all_dict = {'_client': <pyrogram.client.Client object at 0x0000025C05D66720>,
 'animation': None,
 'audio': None,
 'author_signature': 'Владимир Гусевский',
 'caption': '⚡️ Stellar Blade выйдет на ПК в 2025 году — теперь официально.\n'
            '\n'
            'Студия Shift Up написала об этом в своём квартальном отчёте.\n'
            '\n'
            '🕹КиберТопор — Подписаться',
 'caption_entities': pyrogram.types.List([pyrogram.types.MessageEntity(type=pyrogram.enums.MessageEntityType.CUSTOM_EMOJI, offset=0, length=2, custom_emoji_id=5456140674028019486),pyrogram.types.MessageEntity(type=pyrogram.enums.MessageEntityType.BOLD, offset=2, length=40),pyrogram.types.MessageEntity(type=pyrogram.enums.MessageEntityType.TEXT_LINK, offset=128, length=24, url='https://t.me/+6fyKjmOWmW5lYzMy')]),
 'channel_chat_created': None,
 'chat': pyrogram.types.Chat(id=-1001847140757, type=pyrogram.enums.ChatType.CHANNEL, is_verified=False, is_restricted=False, is_creator=True, is_scam=False, is_fake=False, title='test_english', has_protected_content=False),
 'command': None,
 'contact': None,
 'date': datetime.datetime(2024, 11, 12, 15, 38, 28),
 'delete_chat_photo': None,
 'dice': None,
 'document': None,
 'edit_date': None,
 'empty': None,
 'entities': None,
 'forward_date': datetime.datetime(2024, 11, 12, 13, 26, 2),
 'forward_from': None,
 'forward_from_chat': pyrogram.types.Chat(id=-1001966291562, type=pyrogram.enums.ChatType.CHANNEL, is_verified=False, is_restricted=False, is_creator=False, is_scam=False, is_fake=False, title='КиберТопор', photo=pyrogram.types.ChatPhoto(small_file_id='AQADAgADMcoxG94FgUgAEAIAA5a1J7YW____8jY7pkvQWeQABB4E', small_photo_unique_id='AgADMcoxG94FgUg', big_file_id='AQADAgADMcoxG94FgUgAEAMAA5a1J7YW____8jY7pkvQWeQABB4E', big_photo_unique_id='AgADMcoxG94FgUg'), dc_id=2, has_protected_content=False),
 'forward_from_message_id': 18444,
 'forward_sender_name': None,
 'forward_signature': None,
 'forwards': 0,
 'from_scheduled': False,
 'from_user': None,
 'game': None,
 'game_high_score': None,
 'group_chat_created': None,
 'has_media_spoiler': False,
 'has_protected_content': False,
 'id': 355,
 'left_chat_member': None,
 'location': None,
 'matches': None,
 'media': pyrogram.enums.MessageMediaType.VIDEO,
 'media_group_id': None,
 'mentioned': False,
 'migrate_from_chat_id': None,
 'migrate_to_chat_id': None,
 'new_chat_members': None,
 'new_chat_photo': None,
 'new_chat_title': None,
 'outgoing': True,
 'photo': None,
 'pinned_message': None,
 'poll': None,
 'reactions': None,
 'reply_markup': None,
 'reply_to_message': None,
 'reply_to_message_id': None,
 'reply_to_top_message_id': None,
 'scheduled': False,
 'sender_chat': pyrogram.types.Chat(id=-1001847140757, type=pyrogram.enums.ChatType.CHANNEL, is_verified=False, is_restricted=False, is_creator=True, is_scam=False, is_fake=False, title='test_english', has_protected_content=False),
 'service': None,
 'sticker': None,
 'supergroup_chat_created': None,
 'text': None,
 'venue': None,
 'via_bot': None,
 'video': pyrogram.types.Video(file_id='BAACAgIAAx0EbhkhlQACAWNnM0xFdcEBh7F5yBy1xb5ohrSVTQAC_GQAAuppmEl5zexnhiaN9R4E', file_unique_id='AgAD_GQAAuppmEk', width=1280, height=720, duration=18, file_name='IMG_3111.MP4', mime_type='video/mp4', file_size=6919565, supports_streaming=True, date=datetime.datetime(2024, 11, 12, 13, 27, 17), thumbs=[pyrogram.types.Thumbnail(file_id='AAMCAgADHQRuGSGVAAIBY2czTEV1wQGHsXnIHLXFvmiGtJVNAAL8ZAAC6mmYSXnN7GeGJo31AAgBAAdtAAceBA', file_unique_id='AgAD_GQAAuppmEk', width=320, height=180, file_size=6747)]),
 'video_chat_ended': None,
 'video_chat_members_invited': None,
 'video_chat_scheduled': None,
 'video_chat_started': None,
 'video_note': None,
 'views': 1,
 'voice': None,
 'web_app_data': None,
 'web_page': None}